### ISSUE TITLE
BottomSheet Issue

### ISSUE THREAD

**Issue by MiddletonTech** [afsalkodasseri/KalendarView#1]
Great calendar, it was very easy to implement, but I noticed that when using your calendar with a BottomSheetDialog that it moves the view when you change months. As an example I started with April and the View was at the bottom of the screen, when I switched to May it moved it to the top of the screen. It would continue this for each month, going from bottom to top, but when using a regular calendar it does not do this.

Also, is there a listener for when the user changes months? This way I don't have to load the whole database of events, I can just do it for the selected month. Or a way to allow them to swipe from left or right to change months?

**Comment by afsalkodasseri** [comment]
Thanks for reporting this issue.

I will check it and fix soon.
Month swipe changing is not implemented yet.

**Comment by afsalkodasseri** [comment]
Month change listener was there already.

You can set it by 
`setMonthChanger(MonthChanger mChanger)`

**Comment by afsalkodasseri** [comment]
Hi @MiddletonTech ,
I have updated the library by fixing the bug that you reported.

I have added an extra feature also to animate the month changes. You can disable the month changing animation in xml. 
Please refer the ReadMe for the library version and attribute name.
And the swipe to month change will add later.

Hope it helps.
**Thanks**
